name: deploy

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./svelte

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm
          cache-dependency-path: ./svelte/package-lock.json

      - run: npm install

      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          publish_dir: ./svelte/build